### GET USER DATA
GET http://localhost:3000/users/9db38c4a-d243-4583-93fb-fb6ec26988e4 HTTP/1.1

### POST LOG THE USER IN
POST http://localhost:3000/login HTTP/1.1
Content-Type: application/json

{
    "username": "alice",
    "passcode": "alice"
}

### GET SIGN UP DATA
GET http://localhost:3000/ HTTP/1.1
Accept-Version: 1.0.0

### GET AUTH
GET http://localhost:3000/auth HTTP/1.1
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ik1pa2UiLCJpYXQiOjE2ODMyNzczNzZ9.VCAy1vOkFcOGx5BmCp4WjZcPnRO50M0dtRWmzaWRpew
